=== cynthiateeters/cattlelog/creature.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/cynthiateeters/cattlelog/creature.schema.json",
  "title": "Cattlelog Creature",
  "description": "Schema for ASCII art creature files in the cattlelog gallery",
  "type": "object",
  "required": ["name", "author", "source", "tags", "dateAdded", "art"],
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string",
      "description": "Reference to this schema file for VS Code validation"
    },
    "name": {
      "type": "string",
      "minLength": 1,
      "maxLength": 50,
      "description": "Display name for the creature (e.g., 'Tux the Penguin')"
    },
    "author": {
      "type": "string",
      "minLength": 1,
      "description": "Creator's name"
    },
    "source": {
      "type": "string",
      "enum": ["original", "student", "community"],
      "description": "Origin: 'original' (from cowsay), 'student' (class contribution), 'community' (external)"
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      },
      "description": "Categories for filtering (e.g., ['animal', 'classic'])"
    },
    "dateAdded": {
      "type": "string",
      "format": "date",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}$",
      "description": "ISO date when added (YYYY-MM-DD)"
    },
    "art": {
      "type": "string",
      "minLength": 1,
      "description": "ASCII art with placeholders: $thoughts, $eyes, $tongue"
    }
  }
}

=== cynthiateeters/cattlelog/src/cows/14dd05.json
{
  "name": "Yasuna_11",
  "author": "Tony Monroe",
  "source": "original",
  "tags": [],
  "dateAdded": "2026-02-12",
  "art": "  $thoughts\n   $thoughts          . .: -ーー― :._\n    $thoughts       ／.: .: .: .:     ＞  r⌒ヽ\n           / .:         ｜.､.:＼  ﾉ ノ\n          .: .: .:|＼  |斗ﾍﾄ.:.:Ｖ  /\n          |: .: /\\|ノ＼| ／ Ｖ::Ｎ./\n          |: .:/ c─-        Ｙ:| /\n          |:ﾊ:{``   ,  --┐  人V /\n          ﾉ:L＼>   く_,￣┘／  ＼\n   /⌒￣￣￣|￣￣＞--r-rｭ＜|   ／\n   L_,vー─-|    ､ }  ＶYﾊ   Y\n             ￣￣Ｖ  ｜/∧   ﾍ\n                  {   |//∧  ﾍ\n                  {    ＼//   ﾍ\n                  {            ＼\n                  ｝             >"
}

=== cynthiateeters/cattlelog/src/cows/636f87.json
{
  "name": "Psychiatrichelp",
  "author": "Tony Monroe",
  "source": "original",
  "tags": [],
  "dateAdded": "2026-02-12",
  "art": "$thoughts         ____________________\n         $thoughts       |                    |\n          $thoughts      |     PSYCHIATRIC    |\n           $thoughts     |        HELP        |\n            $thoughts    |____________________|\n             $thoughts   ||  ,-..'``.        ||\n              $thoughts  || (,-..'`. )       ||\n                 ||   )-c - `)\\      ||\n   ,.,._.-.,_,.,-||,.(`.--  ,`',.-,_,||.-.,.,-,._.\n              ___||____,`,'--._______||\n             |`._||______`'__________||\n             |   ||     __           ||\n             |   ||    |.-' ,|-      ||\n   _,_,,..-,_|   ||    ._)) `|-      ||,.,_,_.-.,_\n            . `._||__________________||   ____    .\n     .              .           .     . <.____`>\n   .SSt  .      .     .      .    .   _.()`'()`'  ."
}

=== cynthiateeters/cattlelog/src/cows/08b93c.json
{
  "name": "Cake",
  "author": "Tony Monroe",
  "source": "original",
  "tags": [],
  "dateAdded": "2026-02-12",
  "art": "$thoughts\n     $thoughts\n            ,:/+/-\n            /M/              .,-=;//;-\n       .:/= ;MH/,    ,=/+%\\$XH@MM#@:\n      -\\$##@+\\$###@H@MMM#######H:.    -/H#\n .,H@H@ X######@ -H#####@+-     -+H###@X\n  .,@##H;      +XM##M/,     =%@###@X;-\nX%-  :M##########$.    .:%M###@%:\nM##H,   +H@@@$/-.  ,;\\$M###@%,          -\nM####M=,,---,.-%%H####M\\$:          ,+@##\n@##################@/.         :%H##@\\$-\nM###############H,         ;HM##M\\$=\n\\#################.    .=\\$M##M\\$=\n\\#################H..;XM##M\\$=          .:+\nM###################@%=           =+@MH%\n@################M/.          =+H#X%=\n=+M##############M,       -/X#X+;.\n  .;XM##########H=    ,/X#H+:,\n     .=+HM######M+/+HM@+=.\n         ,:/%XM####H/.\n              ,.:=-."
}

=== cynthiateeters/cattlelog/src/cows/b22eaf.json
{
  "name": "Catfence",
  "author": "Tony Monroe",
  "source": "original",
  "tags": [],
  "dateAdded": "2026-02-12",
  "art": "$thoughts     *     ,MMM8&&&.            *\n                  MMMM88&&&&&    .\n        $thoughts        MMMM88&&&&&&&\n     *           MMM88&&&&&&&&\n         $thoughts       MMM88&&&&&&&&\n                 'MMM88&&&&&&'\n          $thoughts        'MMM8&&&'      *\n          |\\\\___/|\n         =) $eyeY$eye (=            .              '\n          \\\\  ^  /\n           )=*=(       *\n          /     \\\\\n          |     |\n         /| | | |\\\\\n         \\\\| | |_|/\\\\\n  _/\\\\_/\\\\_//_// ___/\\\\_/\\\\_/\\\\_/\\\\_/\\\\_/\\\\_/\\\\_/\\\\_/\\\\_\n  |  |  |  | \\\\_) |  |  |  |  |  |  |  |  |  |\n  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |\n  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |     \n  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |\n  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |"
}

=== cynthiateeters/cattlelog/src/cows/c959b8.json
{
  "name": "Spidercow",
  "author": "Tony Monroe",
  "source": "original",
  "tags": [],
  "dateAdded": "2026-02-12",
  "art": "$thoughts     (\n           $thoughts     )\n            $thoughts   (\n         /\\\\  .-\"\"\"\"-.  /\\\\\n        //\\\\\\\\/  ,,,,  \\\\//\\\\\\\\\n        |/\\\\| ,;;;;;;, |/\\\\|\n        //\\\\\\\\\\\\;-\"\"\"\"-;///\\\\\\\\\n       //  \\\\/   ..   \\\\/  \\\\\\\\\n      (| ,-_| \\\\ || / |_-, |)\n        //`__(\\\\(__)/)__`\\\\\\\\\n       // /.-\\\\`($eyes)'/-.\\\\ \\\\\\\\\n      (\\\\ |)   ')  ('   (| /)\n       ` (|   (o  o)   |) `\n         \\\\)    `--'    (/\n                $tongue"
}

=== cynthiateeters/cattlelog/src/cows/e6b56a.json
{
  "name": "Atat",
  "author": "Tony Monroe",
  "source": "original",
  "tags": [],
  "dateAdded": "2026-02-12",
  "art": "$thoughts                         ________\n   $thoughts                    _.-Y  |  |  Y-.,_\n    $thoughts                .-\"   |  |  |  ||   \"~-.      \n          _____     |\"\"[]\"|\" !\"\"! \"|\"==\"\" \"I      \n       .-\"{-. \"I----]_   :|------..| []  __L      \n      P-=}=(r\\_I]_[L__] _l|______l |..  |___I     \n      ^-=\\[_c=-'  ~j______[________]_L______L]    \n                    [_L--.\\_==I|I==/.--.j_I_/     \n                      j)==([\"-----`])==((_]       \n                       I--I\"~~\"\"\"~~\"I--I          \n                       |[]|         |[]|          \n                       j__l         j__l          \n                       |!!|         |!!|          \n                       |..|         |..|         \n                       )[](         )[](          \n                       ]--[         ]--[          \n                       [L_]         [L_]          \n                      /|..|\\       /|..|\\         \n                     '={--}=`     '={--}=`        \n                    .-^-r--^-.   .-^-r--^-.       \n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\nModified ATAT from Row  (the Ascii-Wizard of Oz)"
}

=== cynthiateeters/cattlelog/src/cows/36620f.json
{
  "name": "Chito",
  "author": "Tony Monroe",
  "source": "original",
  "tags": [],
  "dateAdded": "2026-02-12",
  "art": "$thoughts\n    $thoughts\n                -一     一-\n        ／                       ＼\n       /             ________\n      /     -~                     ミ､\n      レ'     _  一ｧiァ ￢}￣Tii一- _  ＼\n    ／    --::|::::/斗士  /   |[_Vい＿＞」\n  ／ イ「::::|:::Y/  ｲ::ハ      ｨ-ﾐヽい\n  ＜___｜:::へ|::|{ 乂-夕     {::ｄﾘ|い\n        ＼八 |::｜             `''   ﾊ|\n    ＿ --＼ヽ|::|                  .ｲ ﾘ\n  ／------.ゝ|:ﾄ|        -       ィ:|\n  ＼        ＞ミ|`ヽ!ﾆ  T  ﾌ￣.≧｜:/\n     ∨         |::\\/ }-/く＼   /｜/"
}

=== cynthiateeters/cattlelog/src/cows/e51e1c.json
{
  "name": "Kiss",
  "author": "Tony Monroe",
  "source": "original",
  "tags": [],
  "dateAdded": "2026-02-12",
  "art": "$thoughts\n      $thoughts\n             ,;;;;;;;,\n            ;;;;;;;;;;;,\n           ;;;;;'_____;'\n           ;;;(/))))|((\\\n           _;;((((((|))))\n          / |_\\\\\\\\\\\\\\\\\\\\\\\\\n     .--~(  \\ ~))))))))))))\n    /     \\  `\\-(((((((((((\\\\\n    |    | `\\   ) |\\       /|)\n     |    |  `. _/  \\_____/ |\n      |    , `\\~            /\n       |    \\  \\           /\n      | `.   `\\|          /\n      |   ~-   `\\        /\n       \\____~._/~ -_,   (\\\n        |-----|\\   \\    ';;\n       |      | :;;;'     \\\n      |  /    |            |\n      |       |            |"
}
