=== cynthiateeters/cattlelog/creature.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/cynthiateeters/cattlelog/creature.schema.json",
  "title": "Cattlelog Creature",
  "description": "Schema for ASCII art creature files in the cattlelog gallery",
  "type": "object",
  "required": ["name", "author", "source", "tags", "dateAdded", "art"],
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string",
      "description": "Reference to this schema file for VS Code validation"
    },
    "name": {
      "type": "string",
      "minLength": 1,
      "maxLength": 50,
      "description": "Display name for the creature (e.g., 'Tux the Penguin')"
    },
    "author": {
      "type": "string",
      "minLength": 1,
      "description": "Creator's name"
    },
    "source": {
      "type": "string",
      "enum": ["original", "student", "community"],
      "description": "Origin: 'original' (from cowsay), 'student' (class contribution), 'community' (external)"
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      },
      "description": "Categories for filtering (e.g., ['animal', 'classic'])"
    },
    "dateAdded": {
      "type": "string",
      "format": "date",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}$",
      "description": "ISO date when added (YYYY-MM-DD)"
    },
    "art": {
      "type": "string",
      "minLength": 1,
      "description": "ASCII art with placeholders: $thoughts, $eyes, $tongue"
    }
  }
}

=== cynthiateeters/cattlelog/src/cows/f796a1.json
{
  "name": "Lobster",
  "author": "Tony Monroe",
  "source": "original",
  "tags": [],
  "dateAdded": "2026-02-12",
  "art": "             $thoughts\n              $thoughts\n                             ,.---._\n                   ,,,,     /       `,\n                    \\\\\\\\   /    '\\_  ;\n                     |||| /\\/``-.__\\;'\n                     ::::/\\/_\n     {{`-.__.-'(`(^^(^^^(^ 9 `.========='\n    {{{{{{ { ( ( (  (   (-----:=\n     {{.-'~~'-.(,(,,(,,,(__6_.'=========.\n                     ::::\\/\\\n                     |||| \\/\\  ,-'/,\n                    ////   \\ `` _/ ;\n                   ''''     \\  `  .'\n                             `---'"
}

=== cynthiateeters/cattlelog/src/cows/40bf92.json
{
  "name": "Skeleton",
  "author": "Tony Monroe",
  "source": "original",
  "tags": [],
  "dateAdded": "2026-02-12",
  "art": "          $thoughts      (__)      \n           $thoughts     /$eyes|  \n            $thoughts   (_\"_)*+++++++++*\n                   //I#\\\\\\\\\\\\\\\\I\\\n                   I[I|I|||||I I `\n                   I`I'///'' I I\n                   I I       I I\n                   ~ ~       ~ ~\n                     Scowleton"
}

=== cynthiateeters/cattlelog/src/cows/36e526.json
{
  "name": "Hiya",
  "author": "Tony Monroe",
  "source": "original",
  "tags": [],
  "dateAdded": "2026-02-12",
  "art": "           $thoughts     (      )\n            $thoughts    ~(^^^^)~\n             $thoughts    ) $eyes \\~_          |\\\n              $thoughts  /     | \\        \\~ /\n                ( 0  0  ) \\        | |\n                 ---___/~  \\       | |\n                  /'__/ |   ~-_____/ |\n   o          _   ~----~      ___---~\n     O       //     |         |\n            ((~\\  _|         -|\n      o  O //-_ \\/ |        ~  |\n           ^   \\_ /         ~  |\n                  |          ~ |\n                  |     /     ~ |\n                  |     (       |\n                   \\     \\      /\\\n                  / -_____-\\   \\ ~~-*\n                  |  /       \\  \\       .==.\n                  / /         / /       |  |\n                /~  |      //~  |       |__|         W<\n                ~~~~        ~~~~"
}

=== cynthiateeters/cattlelog/src/cows/5d7b9f.json
{
  "name": "Jellyfish",
  "author": "Tony Monroe",
  "source": "original",
  "tags": [],
  "dateAdded": "2026-02-12",
  "art": "     $thoughts\n      $thoughts\n\n         .-;\\':\\':\\'-.\n        {\\'.\\'.\\'.\\'.\\'.}\n         )        \\'`.\n        \\'-. ._ ,_.-=\\'\n          `). ( `);(\n          (\\'. .)(,\\'.)\n           ) ( ,\\').(\n          ( .\\').\\'(\\').\n          .) (\\' ).(\\'\n           '  ) (  ).\n            .\\'( .)\\'\n              .).\\'\njgs"
}

=== cynthiateeters/cattlelog/src/cows/31c294.json
{
  "name": "Ghostbusters",
  "author": "Tony Monroe",
  "source": "original",
  "tags": [],
  "dateAdded": "2026-02-12",
  "art": "$thoughts\n           $thoughts\n            $thoughts          __---__\n                    _-       /--______\n               __--( /     \\ )XXXXXXXXXXX\\v.\n             .-XXX(   $eye   $eye  )XXXXXXXXXXXXXXX-\n            /XXX(       U     )        XXXXXXX\\\n          /XXXXX(              )--_  XXXXXXXXXXX\\\n         /XXXXX/ (      O     )   XXXXXX   \\XXXXX\\\n         XXXXX/   /            XXXXXX   \\__ \\XXXXX\n         XXXXXX__/          XXXXXX         \\__---->\n ---___  XXX__/          XXXXXX      \\__         /\n   \\-  --__/   ___/\\  XXXXXX            /  ___--/=\n    \\-\\    ___/    XXXXXX              '--- XXXXXX\n       \\-\\/XXX\\ XXXXXX                      /XXXXX\n         \\XXXXXXXXX   \\                    /XXXXX/\n          \\XXXXXX      >                 _/XXXXX/\n            \\XXXXX--__/              __-- XXXX/\n             -XXXXXXXX---------------  XXXXXX-\n                \\XXXXXXXXXXXXXXXXXXXXXXXXXX/\n                  \"\"VXXXXXXXXXXXXXXXXXXV\"\""
}

=== cynthiateeters/cattlelog/src/cows/54a46f.json
{
  "name": "Yasuna_18",
  "author": "Tony Monroe",
  "source": "original",
  "tags": [],
  "dateAdded": "2026-02-12",
  "art": "   $thoughts\n    $thoughts\n                      ,:二二二二:. .,\n                   ／.／＿＿＿_  ＼.:＼\n                  /. /／.: .: .:＼  : .:＼\n                 /.: .: .:/｜:/\\ .:＼}.: .:.\n                .: |.:/一/ |:/ 一.:}: .: .:｜\n                |.:|ノ |/_｜/ _  \\/ﾍ: .: .:|\n                |.: ｜= ＝    ＝＝= \\/}: .:|\n                |:: ﾘ''           '' /:/､.:|\n               ノ:|:人    一一 ､    /:/ ﾉ.:|\n                , ┴＜＼  {     ｝ ,{:/イ::八\n               /_..   ＼` ー┬一r＜:八八／\n               ／  T＼   `＜}ゞ=彡'⌒＼＼_>\n              /___ |  >､    ｀''＼   ｜\n             /ﾆ}::\\/／  ＼       ｜  ｜\n          　{ﾆﾉ:: /''＼ | `|r--ｯ＜|_／|\n           /__   V    ｝|  》=《      |\n           ＼ ＼/｀一ﾍノ|  { 6 }     ｛ \n             ￣        ｢   ゞ= '      }\n                      ﾉ               〉"
}

=== cynthiateeters/cattlelog/src/cows/6349f9.json
{
  "name": "Atom",
  "author": "Tony Monroe",
  "source": "original",
  "tags": [],
  "dateAdded": "2026-02-12",
  "art": "$thoughts\n        $thoughts\n                  =/;;/-\n                 +:    //\n                /;      /;\n               -X        H.\n .//;;;:;;-,   X=        :+   .-;:=;:;%;.\n M-       ,=;;;#:,      ,:#;;:=,       ,\\@\n :%           :%.=/++++/=.\\$=           %=\n  ,%;         %/:+/;,,/++:+/         ;+.\n    ,+/.    ,;\\@+,        ,%H;,    ,/+,\n       ;+;;/= \\@.  .H##X   -X :///+;\n       ;+=;;;.\\@,  .XM\\@\\$.  =X.//;=%/.\n    ,;:      :\\@%=        =\\$H:     .+%-\n  ,%=         %;-///==///-//         =%,\n ;+           :%-;;;:;;;;-X-           +:\n \\@-      .-;;;;M-        =M/;;;-.      -X\n  :;;::;;-.    %-        :+    ,-;;-;:==\n               ,X        H.\n                ;/      %=\n                 //    +;\n                  ,////,"
}

=== cynthiateeters/cattlelog/src/cows/4c6197.json
{
  "name": "Ackbar",
  "author": "Tony Monroe",
  "source": "original",
  "tags": [],
  "dateAdded": "2026-02-12",
  "art": "$thoughts\n          $thoughts\n                      ?IIIIIII7II?????+\n                   ~III777II777I?+==++==+:\n                  ???I7I???I7II++=====++===\n                 ??+??????????+===~~=+++??==+\n                ??+??II??????+==~=~~=+++++==++\n               I+?????????+?+====~=~==+==++?==?\n              ?????II?????+++++=======?===~~~~==\n            ,?????II????????++++====~===::~~~~:~\n            I?I??II?+++??+?+++==~~~~:~:~:,:,,:::~\n           I??????+==+???++++=~~:~:~:,:::,:,,,,,::\n          +I?++++=+=+????+++=~~:~~:::,,,,::,,,:,:\n          I??+?+====+???+++===~~::::,::,:,,,,,,::\n         I????=~===++?+=+=~==~:~~:,,,,,,,.,,,,,:~\n        =??+?=~~~~??+?+===~~==,==~~~~,,,,..,,,.:=\n        II++==~~=++++++=~~=~,~+=?+?=I?++=..,.,,:\n     IIII?+?=====+~+++~=~~~:::=~+~===:,,,,,.,.::\n    I?=?I+??+=~=~?I?=+=~~~::,~~=~::~=::,,,,,,::\n    ?+I??++=++~,::+++~~~:::,,=~~=,~,..,::.:\n    ++=+?++~=:~::I+,~=:~,:,,,,:~~......::~,,,\n     ~=~=:.++~:,.,~=::::.,,:,.:~,:=...==~,::\n     =~?++??+=~~,.:?~.:,:,,,.,::,,~:=~=::,~\n     ++~~:~===~:~,.~::,~=~.:,..,:,,:==:.,:7\n     ~~,::...:=:,::+:~:.,~,...,.,,,,::~,,::~=\n      =~===+=~~,.::,,,:::,..,,,,,,,,,,,:,..,=+?\n      ~=~=~::~~~::,.,,,~:.+,..,,,,..,,,,...,+I?\n      ~==~:~~:~~,~=~~:,:~,:,,,,,,....,,,..+?I?I\n      ~=~=+,:~:=,:~~~~~~::::,.,,.,,.,,,..~+????I\n      ~=~==~=:~~:,~~~~~:::,::,.,,,..,,,I77I?+??II\n      +I7:::~~=~:,::~~~~.=.,~,,,,...,~7III?+??II7\n     777?+~:=~=~~:,::~~:::.,,,,,,,,,777II??I777777\n     777I==:=~::~~~~::~:::,:,:~:::,777I???777777777\n    7777+,~===~:~:~~~~:::,.~:=,,:777II???77777777777=?\n    777I~,~~~=~::~:,:,,,:=~~,,:7777I???I7777777777+=++\n  I7777I,,:,.==::::,:,,,,::::7777I+??I77777777777??I7I7,\n ,77777I::,..~~:,,,,,,.,:~I7777I+??I777777777777?I7777777,\n 77777777,...~~:,,,,,.,77777I7???II777777777777+?7777777777\n77777777777:,~~~,,=7777777I???II777777777777777+77777777777\n77777777777777777777777I+7?7II77777777777777777+777777777777"
}
