=== cynthiateeters/cattlelog/creature.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/cynthiateeters/cattlelog/creature.schema.json",
  "title": "Cattlelog Creature",
  "description": "Schema for ASCII art creature files in the cattlelog gallery",
  "type": "object",
  "required": ["name", "author", "source", "tags", "dateAdded", "art"],
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string",
      "description": "Reference to this schema file for VS Code validation"
    },
    "name": {
      "type": "string",
      "minLength": 1,
      "maxLength": 50,
      "description": "Display name for the creature (e.g., 'Tux the Penguin')"
    },
    "author": {
      "type": "string",
      "minLength": 1,
      "description": "Creator's name"
    },
    "source": {
      "type": "string",
      "enum": ["original", "student", "community"],
      "description": "Origin: 'original' (from cowsay), 'student' (class contribution), 'community' (external)"
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      },
      "description": "Categories for filtering (e.g., ['animal', 'classic'])"
    },
    "dateAdded": {
      "type": "string",
      "format": "date",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}$",
      "description": "ISO date when added (YYYY-MM-DD)"
    },
    "art": {
      "type": "string",
      "minLength": 1,
      "description": "ASCII art with placeholders: $thoughts, $eyes, $tongue"
    }
  }
}

=== cynthiateeters/cattlelog/src/cows/a5130d.json
{
  "name": "Luke koala",
  "author": "Tony Monroe",
  "source": "original",
  "tags": [],
  "dateAdded": "2026-02-12",
  "art": "  $thoughts\n   $thoughts          .\n       ___   //\n     {~$eye_$eye~}// \n      ( Y )K/  \n     ()~*~()   \n     (_)-(_)   \n     Luke    \n     Skywalker\n     koala"
}

=== cynthiateeters/cattlelog/src/cows/e18921.json
{
  "name": "Yasuna_05",
  "author": "Tony Monroe",
  "source": "original",
  "tags": [],
  "dateAdded": "2026-02-12",
  "art": "$thoughts\n    $thoughts\n       ／ .: .: .: .: .: .: .:  .: .: . ＼\n     ./   .: .: .: .: .: .: .:  .: .: .: .ヽ\n     /          /  . ..l..  ヽ.: .: .: .: .:.\n    ,    .. .: /  .| : ハ: .|  ＼.: .: .: .: .\n    |.: .:.l.:/  ヽ|.:/  ､ .|.ノ ＼ .l:.: .: |\n    |.: .:.|:/.ｨ≠ﾐ|:/    ＼| ィ≠ミ､|.:.: .:|\n    |.: .: ノ /Y::::ヽ       Y::::ヽヽ＼ .: ｜\n   /:.: /^|:|{.{:::::}       {:::::}.} |:|ヽ:､\n ノ:ノ: { |:| Ｕうーソ       うーソ  |:| }ヽ:＼\n    | : ヽ|.|  '' ￣           ￣ ''U|:| /:|\n     :: ::人|                        |人::ﾘ\n     Vﾊ:: :: \\                     /::  ﾊ/\n      \\|ヽ:: ::ヽ､     --      ,イ::／|／\n          ＼| ヽ:≧=r-r---r-r=≦:ノ|／\n             . :´:.ヽ二二.ノ: :｀: .\n            ／: : :  ／ハ＼: : : : ＼"
}

=== cynthiateeters/cattlelog/src/cows/87311b.json
{
  "name": "Black mesa",
  "author": "Tony Monroe",
  "source": "original",
  "tags": [],
  "dateAdded": "2026-02-12",
  "art": "    $thoughts\n     $thoughts\n           .-;+\\$XHHHHHHX\\$+;-.\n        ,;X\\@\\@X%/;=----=:/%X\\@\\@X/,\n      =\\$\\@\\@%=.              .=+H\\@X:\n    -XMX:                      =XMX=\n   /\\@\\@:                          =H\\@+\n  %\\@X,                            .\\$\\@\\$\n +\\@X.                               \\$\\@%\n-\\@\\@,                                .\\@\\@=\n%\\@%                                  +\\@\\$\nH\\@:                                  :\\@H\nH\\@:         :HHHHHHHHHHHHHHHHHHX,    =\\@H\n%\\@%         ;\\@M\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@H-   +\\@\\$\n=\\@\\@,        :\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@= .\\@\\@:\n +\\@X        :\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@M\\@\\@\\@\\@\\@\\@:%\\@%\n  \\$\\@\\$,      ;\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@M\\@\\@\\@\\@\\@\\@\\$.\n   +\\@\\@HHHHHHH\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@+\n    =X\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@X=\n      :\\$\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@M\\@\\@\\@\\@\\$:\n        ,;\\$\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@\\@X/-\n           .-;+\\$XXHHHHHX\\$+;-."
}

=== cynthiateeters/cattlelog/src/cows/cc14b7.json
{
  "name": "Ren",
  "author": "Tony Monroe",
  "source": "original",
  "tags": [],
  "dateAdded": "2026-02-12",
  "art": "$thoughts\n    $thoughts\n    ____  \n   /# /_\\\\_\n  |  |/$eye\\\\$eye\\\\\n  |  \\\\\\\\_/_/\n / |_   |  \n|  ||\\\\_ ~| \n|  ||| \\\\/  \n|  |||_    \n \\\\//  |    \n  ||  |    \n  ||_  \\\\   \n  \\\\_|  o|  \n  /\\\\___/   \n /  ||||__ \n    (___)_)"
}

=== cynthiateeters/cattlelog/src/cows/45cfc4.json
{
  "name": "Yasuna_09",
  "author": "Tony Monroe",
  "source": "original",
  "tags": [],
  "dateAdded": "2026-02-12",
  "art": "  $thoughts\n   $thoughts\n    $thoughts\n    \n           ____\n       ,: .: .: :.ヽ\n     ,'       /\\   ｉ\n     {: .:ﾉﾚﾍ/  Viﾍ:}\n    .{,､〈 Ｏ   Ｏ{.:.\n    ノヽ\\!\"       }.:ﾊ\n      Ｗﾊw=-､へ,ｬ<,V'      \n         /ﾍ }{./\\\n        ;: i:V:!;}\n        |:｜: :｜}\n        |:|:｡: ｡l}\n        >-'-ﾟ-'`ﾟu\n        ｰi-i～i-i~\n         |.|  |.|\n         |-|  |-|\n         ヒｺ  ヒｺ"
}

=== cynthiateeters/cattlelog/src/cows/a1a37a.json
{
  "name": "Periodic table",
  "author": "Tony Monroe",
  "source": "original",
  "tags": [],
  "dateAdded": "2026-02-12",
  "art": "$thoughts\n $thoughts\n   1A   2A                                         3A  4A  5A  6A  7A  8A\n  -----                                                               -----\n1 | H |                                                               |He |\n  |---+----                                       --------------------+---|\n2 |Li |Be |                                       | B | C | N | O | F |Ne |\n  |---+---|                                       |---+---+---+---+---+---|\n3 |Na |Mg |3B  4B  5B  6B  7B |    8B     |1B  2B |Al |Si | P | S |Cl |Ar |\n  |---+---+---------------------------------------+---+---+---+---+---+---|\n4 | K |Ca |Sc |Ti | V |Cr |Mn |Fe |Co |Ni |Cu |Zn |Ga |Ge |As |Se |Br |Kr |\n  |---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---|\n5 |Rb |Sr | Y |Zr |Nb |Mo |Tc |Ru |Rh |Pd |Ag |Cd |In |Sn |Sb |Te | I |Xe |\n  |---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---|\n6 |Cs |Ba |Lu |Hf |Ta | W |Re |Os |Ir |Pt |Au |Hg |Tl |Pb |Bi |Po |At |Rn |\n  |---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---|\n7 |Fr |Ra |Lr |Rf |Db |Sg |Bh |Hs |Mt |Ds |Rg |Cn |Nh |Fl |Mc |Lv |Ts |Og |\n  -------------------------------------------------------------------------\n              -------------------------------------------------------------\n   Lanthanide |La |Ce |Pr |Nd |Pm |Sm |Eu |Gd |Tb |Dy |Ho |Er |Tm |Yb |Lu |\n              |---+---+---+---+---+---+---+---+---+---+---+---+---+---+---|\n   Actinide   |Ac |Th |Pa | U |Np |Pu |Am |Cm |Bk |Cf |Es |Fm |Md |No |Lr |\n              -------------------------------------------------------------"
}

=== cynthiateeters/cattlelog/src/cows/d3c038.json
{
  "name": "Cube",
  "author": "Tony Monroe",
  "source": "original",
  "tags": [],
  "dateAdded": "2026-02-12",
  "art": "   $thoughts\n    $thoughts\n       ____________\n      /\\  ________ \\\n     / /\\ \\______/\\ \\\n    / / /\\ \\  / /\\ \\ \\\n   / / /__\\ \\/ / /\\ \\ \\\n  / /_/____\\ \\/_/__\\_\\ \\\n  \\ \\ \\____/ / ________ \\\n   \\ \\ \\  / / /\\ \\  / / /\n    \\ \\ \\/ / /\\ \\ \\/ / /\n     \\ \\/ / /__\\_\\/ / /\n      \\  / /______\\/ /\n       \\/___________/"
}

=== cynthiateeters/cattlelog/src/cows/21d176.json
{
  "name": "Maze runner",
  "author": "Tony Monroe",
  "source": "original",
  "tags": [],
  "dateAdded": "2026-02-12",
  "art": "    $thoughts\n     $thoughts\n      $thoughts\n       \\\n        \\\n         \\\n    \\     \\                     /\n     \\     \\                   /\n      \\     \\                 /\n       ]     \\               [    ,'|\n       ]      \\              [   /  |\n       ]___               ___[ ,'   |\n       ]  ]\\             /[  [ |:   |\n       ]  ] \\           / [  [ |:   |\n       ]  ]  ]         [  [  [ |:   |\n       ]  ]  ]__     __[  [  [ |:   |\n       ]  ]  ] ]\\ _ /[ [  [  [ |:   |\n       ]  ]  ] ] (#) [ [  [  [ :===='\n       ]  ]  ]_].nHn.[_[  [  [\n       ]  ]  ]  HHHHH. [  [  [\n       ]  ] /   `HH(\"N  \\ [  [\n       ]__]/     HHH  \"  \\[__[\n       ]         NNN         [\n       ]         N/\"         [\n       ]         N H         [\n      /          N            \\\n     /           q,            \\\n    /                           \\"
}
